# Generated by Django 3.2.6 on 2021-08-12 19:10

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hordak', '0028_auto_20210811_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leg',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=4, default_currency='EUR', help_text='Record debits as positive, credits as negative', max_digits=19, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='statementline',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=19, verbose_name='amount'),
        ),
    ]
